### ISSUE TITLE
Inconsistency "username" in request != "name" in JWT

### ISSUE THREAD

**Issue by olibre** [synw/quid#5]
The Quid API expects `"username"` within a request body JSON:
https://github.com/synw/quid/blob/master/quidlib/server/api/token.go#L223

But the Quid JWTs contain `"name"` for the same meaning:
https://github.com/synw/quid/blob/master/quidlib/tokens/claims.go

The database tables also use `"name"`:
https://github.com/synw/quid/blob/master/quidlib/server/models.go

**Comment by synw** [comment]
We probably should use `username" all over the place as it is more specific

**Comment by olibre** [comment]
Hi @synw 
What do you think to use `user` instead of `username`?

The request for a new `token/refresh` using `"user"`:

```php
curl -X POST http://localhost:8082/token/refresh/10m          \
     -H 'Content-Type: application/json'                      \
     -d '{"namespace":"xxx", "user":"xxx", "password":"xxx"}'
```

The content of a token (JWT) with `"user"`:

```yaml
{
    "namespace": "xxx", 
    "user": "xxx", 
    "groups": ["xx1", "xx2"], 
    "exp": 1595950745
}
```
